spring:
 cloud:
   gateway:
     routes:
       - id: cactus-user-panel
         uri: lb://CACTUS-USER-PANEL
         predicates:
           - Path=/api/panel/**
         filters:
           - JwtAuthenticationFilter
           
       - id: calendar-service
         uri: lb://CALENDAR-SERVICE
         predicates:
           - Path=/calendar/**
         filters:
           - JwtAuthenticationFilter
           
       - id: forecast-service
         uri: lb://FORECAST-SERVICE
         predicates:
           - Path=/forecast/**
         filters:
           - JwtAuthenticationFilter
           
       - id: plans-service
         uri: lb://PLANS-SERVICE
         predicates:
           - Path=/plans/**
         filters:
           - JwtAuthenticationFilter
              
 application:
    name: CACTUS-API-GATEWAY
    
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/